# Generated by Django 4.2.1 on 2023-06-10 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DatosDomicilio', '0001_initial'),
        ('Facturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TiemposEntrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEntrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idDatoDomicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatosDomicilio.datodomicilio')),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturas.factura')),
                ('idTiemposEntrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiemposEntrega.tiempoentrega')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado Entrega',
                'verbose_name_plural': 'Estados Entrega',
                'db_table': 'EstadoEntrega',
                'ordering': ['id'],
            },
        ),
    ]
