# Generated by Django 4.2.1 on 2023-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstadoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoEstadoPago', models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Estado Pago')),
            ],
            options={
                'verbose_name': 'Tipo Estado Pago',
                'verbose_name_plural': 'Tipos Estados Pago',
                'db_table': 'TipoEstadoPago',
                'ordering': ['id'],
            },
        ),
    ]
