# Generated by Django 4.2.1 on 2023-06-10 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EstadosPedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('FechaRegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombreTipoEstadoPago', models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Estado Pago')),
                ('idEstadoPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstadosPedidos.estadopedido')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedido',
                'ordering': ['id'],
            },
        ),
    ]
