# Generated by Django 4.2.1 on 2023-06-12 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='idProducto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
            preserve_default=False,
        ),
    ]
