# Generated by Django 4.2.1 on 2023-05-16 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDatoDomicilio', models.IntegerField(default=' ', verbose_name='Identificador Nombre Domicilio')),
                ('ciudad', models.CharField(default=' ', max_length=45, verbose_name='Ciudad')),
                ('localidad', models.CharField(default=' ', max_length=45, verbose_name='Localidad')),
                ('barrio', models.CharField(default=' ', max_length=45, verbose_name='Barrio')),
                ('direccion', models.CharField(default=' ', max_length=45, verbose_name='Direccion')),
                ('descripcionDomicilio', models.CharField(default=' ', max_length=200, verbose_name='Descripcion Domicilio')),
            ],
            options={
                'verbose_name': 'Dato Domicilio',
                'verbose_name_plural': 'Datos Domicilio',
                'db_table': 'DatoDomicilio',
                'ordering': ['idDatoDomicilio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEstadoEntrega', models.IntegerField(default=' ', verbose_name='Identificador Estado Entrega')),
                ('nombres', models.CharField(default=' ', max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(default=' ', max_length=45, verbose_name='Apellidos')),
                ('correo', models.EmailField(default=' ', max_length=254, unique=True, verbose_name='Correo')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('mensaje', models.CharField(default=' ', max_length=200, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Registro Mensaje',
                'verbose_name_plural': 'Registros Mensajes',
                'db_table': 'RegistroMensajes',
                'ordering': ['idEstadoEntrega'],
            },
        ),
        migrations.AlterModelOptions(
            name='estadoentrega',
            options={'ordering': ['idEstadoEntrega'], 'verbose_name': 'Estado Entrega', 'verbose_name_plural': 'Estados Entrega'},
        ),
        migrations.AlterModelOptions(
            name='estadopedido',
            options={'ordering': ['idEstadoPedido'], 'verbose_name': 'Estado Pedido', 'verbose_name_plural': 'Estados Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['idFactura'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['idNotificacion'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['idPedido'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='tiempoentrega',
            options={'ordering': ['idTiempoEntrega'], 'verbose_name': 'Tiempo Entrega', 'verbose_name_plural': 'Tiempos Entrega'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['idTipoDocumento'], 'verbose_name': 'Tipo Documento', 'verbose_name_plural': 'Tipos Documentos'},
        ),
        migrations.AlterModelOptions(
            name='tipoestadopago',
            options={'ordering': ['idTipoEstadoPago'], 'verbose_name': 'Tipo Estado Pago', 'verbose_name_plural': 'Tipos Estados Pago'},
        ),
        migrations.AlterModelOptions(
            name='tipoestadopedido',
            options={'ordering': ['idTipoEstadoPedido'], 'verbose_name': 'Tipo Estado Pedido', 'verbose_name_plural': 'Tipos Estados Pedido'},
        ),
        migrations.AlterModelOptions(
            name='tipometodopago',
            options={'ordering': ['idTipoMetodoPago'], 'verbose_name': 'Tipo Metodo Pago', 'verbose_name_plural': 'Tipos Metodos Pago'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['idUsuario'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='tiempoentrega',
            name='cantidaTiempoEntrega',
        ),
        migrations.AddField(
            model_name='tiempoentrega',
            name='cantidadTiempoEntrega',
            field=models.IntegerField(default=' ', verbose_name='Cantidad Tiempo Entrega'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='nombreTipoDocumento',
            field=models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='estadoentrega',
            name='idEstadoEntrega',
            field=models.IntegerField(default=' ', verbose_name='Identificador Estado Entrega'),
        ),
        migrations.AlterField(
            model_name='estadoentrega',
            name='nombreTipoEstadoPago',
            field=models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Estado Pago'),
        ),
        migrations.AlterField(
            model_name='estadopedido',
            name='idEstadoPedido',
            field=models.IntegerField(default=' ', verbose_name='Identficador Estado Pedido'),
        ),
        migrations.AlterField(
            model_name='estadopedido',
            name='nombreEstadoPedido',
            field=models.CharField(default=' ', max_length=45, verbose_name='Nombre Estado Pedido'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fechaFactura',
            field=models.DateTimeField(default=' ', verbose_name='Fecha Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idFactura',
            field=models.IntegerField(default=' ', verbose_name='Identificador Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='valorPedido',
            field=models.IntegerField(default=' ', verbose_name='Valor Pedido'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='idNotificacion',
            field=models.IntegerField(default=' ', verbose_name='Identificador Notificacion'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idPedido',
            field=models.IntegerField(default=' ', verbose_name='Identificador Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombreTipoEstadoPago',
            field=models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Estado Pago'),
        ),
        migrations.AlterField(
            model_name='tiempoentrega',
            name='descripcionTiempoEntrega',
            field=models.CharField(default=' ', max_length=200, verbose_name='Descripcion Tiempo Entrega'),
        ),
        migrations.AlterField(
            model_name='tiempoentrega',
            name='idTiempoEntrega',
            field=models.IntegerField(default=' ', verbose_name='Identificador Tiempo Entrega'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='idTipoDocumento',
            field=models.IntegerField(default=' ', verbose_name='Identificador Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='tipoestadopago',
            name='idTipoEstadoPago',
            field=models.IntegerField(default=' ', verbose_name='Identificador Tipo Estado Pago'),
        ),
        migrations.AlterField(
            model_name='tipoestadopago',
            name='nombreTipoEstadoPago',
            field=models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Estado Pago'),
        ),
        migrations.AlterField(
            model_name='tipoestadopedido',
            name='idTipoEstadoPedido',
            field=models.IntegerField(default=' ', verbose_name='Identificador Tipo Estado Pedido'),
        ),
        migrations.AlterField(
            model_name='tipoestadopedido',
            name='nombreTipoEstadoPedido',
            field=models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Estado Pedido'),
        ),
        migrations.AlterField(
            model_name='tipometodopago',
            name='idTipoMetodoPago',
            field=models.IntegerField(default=' ', verbose_name='Identificador Tipo Metodo Pago'),
        ),
        migrations.AlterField(
            model_name='tipometodopago',
            name='nombreTipoMetodoPago',
            field=models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Metodo Pago'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default=' ', max_length=45, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.IntegerField(default=' ', verbose_name='Identificador Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default=' ', max_length=45, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numeroIdentificacion',
            field=models.IntegerField(default=' ', verbose_name='Numero Identificacion'),
        ),
        migrations.AlterModelTable(
            name='estadoentrega',
            table='EstadoEntrega',
        ),
        migrations.AlterModelTable(
            name='estadopedido',
            table='EstadoPedido',
        ),
        migrations.AlterModelTable(
            name='factura',
            table='Factura',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='Notificacion',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='Pedido',
        ),
        migrations.AlterModelTable(
            name='tiempoentrega',
            table='TiempoEntrega',
        ),
        migrations.AlterModelTable(
            name='tipodocumento',
            table='TipoDocumento',
        ),
        migrations.AlterModelTable(
            name='tipoestadopago',
            table='TipoEstadoPago',
        ),
        migrations.AlterModelTable(
            name='tipoestadopedido',
            table='TipoEstadoPedido',
        ),
        migrations.AlterModelTable(
            name='tipometodopago',
            table='TipoMetodoPago',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
        migrations.DeleteModel(
            name='RegistroMensajes',
        ),
        migrations.AddField(
            model_name='registromensaje',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='datosDomicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.datodomicilio'),
        ),
        migrations.DeleteModel(
            name='DatosDomicilio',
        ),
    ]
