# Generated by Django 4.2.1 on 2023-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstadoPedido', models.CharField(default=' ', max_length=45, verbose_name='Nombre Estado Pedido')),
            ],
            options={
                'verbose_name': 'Estado Pedido',
                'verbose_name_plural': 'Estados Pedidos',
                'db_table': 'EstadoPedido',
                'ordering': ['id'],
            },
        ),
    ]
