# Generated by Django 4.2.1 on 2023-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoDocumento', models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Documento')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos Documentos',
                'db_table': 'TipoDocumento',
                'ordering': ['id'],
            },
        ),
    ]
