# Generated by Django 4.2.1 on 2023-06-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EstadosEntrega', '0001_initial'),
        ('Facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoEntrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstadosEntrega.estadoentrega')),
                ('idFatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturas.factura')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'Notificacion',
                'ordering': ['id'],
            },
        ),
    ]
