# Generated by Django 4.2.1 on 2023-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoDomicilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(default=' ', max_length=45, verbose_name='Ciudad')),
                ('localidad', models.CharField(default=' ', max_length=45, verbose_name='Localidad')),
                ('barrio', models.CharField(default=' ', max_length=45, verbose_name='Barrio')),
                ('direccion', models.CharField(default=' ', max_length=45, verbose_name='Direccion')),
                ('descripcionDomicilio', models.CharField(default=' ', max_length=200, verbose_name='Descripcion Domicilio')),
            ],
            options={
                'verbose_name': 'Dato Domicilio',
                'verbose_name_plural': 'Datos Domicilio',
                'db_table': 'DatoDomicilio',
                'ordering': ['ciudad'],
            },
        ),
    ]
