# Generated by Django 4.2.1 on 2023-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMetodoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoMetodoPago', models.CharField(default=' ', max_length=45, verbose_name='Nombre Tipo Metodo Pago')),
            ],
            options={
                'verbose_name': 'Tipo Metodo Pago',
                'verbose_name_plural': 'Tipos Metodos Pago',
                'db_table': 'TipoMetodoPago',
                'ordering': ['id'],
            },
        ),
    ]
