# Generated by Django 4.2.1 on 2023-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(default=' ', max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(default=' ', max_length=45, verbose_name='Apellidos')),
                ('correo', models.EmailField(default=' ', max_length=254, unique=True, verbose_name='Correo')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('mensaje', models.CharField(default=' ', max_length=200, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Registro Mensaje',
                'verbose_name_plural': 'Registros Mensajes',
                'db_table': 'RegistroMensajes',
                'ordering': ['id'],
            },
        ),
    ]
